### ISSUE TITLE
Bug loading rasterra library

### ISSUE THREAD

**Issue by laurenwilner** [collijk/rasterra#25]
When loading the rasterra library, I get the attached error regarding 128-bit floats. I have numpy 2.0 installed and have no other issues using it. I am running the following line of code to load this library and get this error: 

import rasterra as rt

Thanks!
![PHOTO-2024-06-25-07-56-56](https://github.com/collijk/rasterra/assets/117664739/fa0ab4a6-66d0-47ee-b3b6-d82034ef17f1)

**Comment by collijk** [comment]
Fixed in version 0.5.14
